- name: NGINX installtion
  hosts: localhost
  tasks:
    - name: installation of nginx on node server
      ansible.builtin.package:
        name: nginx
        state: present
  tasks:
    - name: starting nginx service
      ansible.builtin.service:
        name: nginx
        state: started
