- name: NGINX installtion
  hosts: web
  - tasks:
      name: installation of nginx on node server
      ansible.builtin.package:
        name: nginx
        state: present
       name: start service
  - tasks:
      name: starting nginx service
      ansible.builtin.service:
        name: ntpdate
        state: started
