- name: variables from PLAY Book
  hosts: localhost
  vars_files:
   - variables.yml
  tasks:
  - name: variables
      ansible.builtin.debug:
        msg: "Hi I am learning {{course}}, Trainer is {{trainer}}, Duriation is {{duration}}"